# Generated by Django 3.2.11 on 2024-01-15 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='test',
            field=models.CharField(default='default', max_length=200),
            preserve_default=False,
        ),
    ]
